project:
  type: website
  output-dir: ../docs

website:
  title: "State of States"
  navbar:
    left:
      - href: index.qmd
        text: Introduction
      - href: most-common.qmd
        text: Most Common Words
      - href: state-sentiment.qmd
        text: Sate Sentiment
      - href: state-mentions.qmd
        text: State Mentions
      - href: conclusion.qmd
        text: Conclusion
      # - href: 
      #   text: Code
  page-footer:
    left: |
      Content © Isfar Baset, Yicheng Zhu, Jiaru He<br>
      Licensed under [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Made with [R](https://www.r-project.org) and [Quarto](https://quarto.org)<br>
      [View source on GitHub](https://github.com/anly503/lab-2.1)

format:
  html:
    theme: cosmo
    css: style.css
    toc: true